# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-19 18:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutinator', '0004_auto_20160907_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='choose_random',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Ansvarlig gruppe'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ansvarlig person'),
        ),
    ]
