# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-24 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20160309_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceevent',
            name='waitlist',
            field=models.BooleanField(default=True, verbose_name='venteliste'),
        ),
    ]
