# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-09-28 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import ldapdb.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LdapGroup',
            fields=[
                ('dn', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('gid', ldapdb.models.fields.IntegerField(blank=True, db_column='gidNumber', unique=True)),
                ('name', ldapdb.models.fields.CharField(db_column='cn', max_length=200, unique=True)),
                ('usernames', ldapdb.models.fields.ListField(blank=True, db_column='memberUid')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LdapOrgUnit',
            fields=[
                ('dn', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', ldapdb.models.fields.CharField(db_column='ou', max_length=200, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LdapUser',
            fields=[
                ('dn', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('first_name', ldapdb.models.fields.CharField(db_column='givenName', max_length=200)),
                ('last_name', ldapdb.models.fields.CharField(db_column='sn', max_length=200)),
                ('full_name', ldapdb.models.fields.CharField(blank=True, db_column='cn', max_length=200)),
                ('email', ldapdb.models.fields.CharField(blank=True, db_column='mail', max_length=200)),
                ('phone', ldapdb.models.fields.CharField(blank=True, db_column='telephoneNumber', max_length=200)),
                ('mobile_phone', ldapdb.models.fields.CharField(blank=True, db_column='mobile', max_length=200)),
                ('photo', ldapdb.models.fields.ImageField(blank=True, db_column='jpegPhoto')),
                ('uid', ldapdb.models.fields.IntegerField(db_column='uidNumber', unique=True)),
                ('group', ldapdb.models.fields.IntegerField(db_column='gidNumber')),
                ('gecos', ldapdb.models.fields.CharField(blank=True, db_column='gecos', max_length=200)),
                ('home_directory', ldapdb.models.fields.CharField(blank=True, db_column='homeDirectory', max_length=200)),
                ('login_shell', ldapdb.models.fields.CharField(db_column='loginShell', default='/bin/bash', max_length=200)),
                ('username', ldapdb.models.fields.CharField(db_column='uid', max_length=200, unique=True)),
                ('password', ldapdb.models.fields.CharField(blank=True, db_column='userPassword', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
