# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-15 18:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_item_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcategory',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'permissions': (('view_itemCategory', 'View Inventory Item Category'),)},
        ),
    ]
