# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-24 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_auto_20160309_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.SmallIntegerField(choices=[(1, 'Umiddelbar'), (2, 'Frist'), (3, 'Utsettelse')], default=3, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_key',
            field=models.CharField(choices=[('trikom', 'trikom'), ('arrkom', 'arrkom'), ('prokom', 'prokom')], default='arrkom', max_length=10, verbose_name='stripe key'),
        ),
    ]
